In [201]:
import numpy as np
import pandas as pd
import seaborn as sb
dataset = pd.read_csv('Facebook_metrics/dataset_Facebook.csv',delimiter=';')
#del dataset['Page total likes']
del dataset['Type']
del dataset['Paid']
#del dataset['Total Interactions']
dataset = dataset.dropna(how='any',axis=0)
mat_1 = dataset.iloc[:,[0,-1]].T
mat_2  =dataset.iloc[:,1:-2].T
dataset = dataset.T

cov_mat = np.cov(dataset)
s_xx = cov_mat[[0,-1],0:2]
s_xy = cov_mat[[0,-1],2:-1]
s_yx = s_xy.T
s_yy = cov_mat[2:-1,2:-1]

w_xx, v_xx = np.linalg.eig(s_xx)
w_xx_inv = w_xx**-0.5
w_xx_inv_p = np.diag(w_xx_inv).reshape(2,2)
e_xx = np.matmul(np.matmul(v_xx,w_xx_inv_p),v_xx.T)

w_yy, v_yy = np.linalg.eig(s_yy)
w_yy_inv = w_yy**-1
w_yy_inv_p = np.diag(w_yy_inv).reshape(14,14)
e_yy = np.matmul(np.matmul(v_yy,w_yy_inv_p),v_yy.T)

m1=np.matmul(e_xx,s_xy)
m2=np.matmul(m1,e_yy)
m3=np.matmul(m2,s_yx)
m4=np.matmul(m3,e_xx)

S = m4

w_S,v_S = np.linalg.eig(S)
w_S_1 = np.reshape(w_S, (1, 2))
#eigen values of S i.e w_S mul XX^1/2 mul X
w_xx, v_xx = np.linalg.eig(s_xx)
w_xx_inv_1 = w_xx**0.5
w_xx_inv_p1 = np.diag(w_xx_inv_1).reshape(2,2)
e_xx_1 = np.matmul(np.matmul(v_xx,w_xx_inv_p1),v_xx.T)

final_1 = np.matmul(np.matmul(w_S_1,e_xx_1),mat_1)
final_1 = final_1.T

#b1
w_yy, v_yy = np.linalg.eig(s_yy)
w_yy_inv = w_yy**-0.5
w_yy_inv_p = np.diag(w_yy_inv).reshape(14,14)
e_yy = np.matmul(np.matmul(v_yy,w_yy_inv_p),v_yy.T)

f_k = np.matmul(np.matmul(np.matmul(w_S_1,e_xx),s_xy),s_yy)
v_1 = np.matmul(np.matmul(f_k,e_yy),mat_2) 
v_1=v_1.T

In [203]:
final_1

array([[1.11425720e+10],
       [1.11440226e+10],
       [1.11421187e+10],
       [1.11805825e+10],
       [1.11492131e+10],
       [1.11445213e+10],
       [1.11466292e+10],
       [1.11479891e+10],
       [1.11446573e+10],
       [1.11435240e+10],
       [1.11460172e+10],
       [1.11427080e+10],
       [1.11426627e+10],
       [1.11437507e+10],
       [1.10718325e+10],
       [1.10607036e+10],
       [1.10594797e+10],
       [1.10744164e+10],
       [1.10599557e+10],
       [1.10592077e+10],
       [1.10600917e+10],
       [1.10582557e+10],
       [1.10586637e+10],
       [1.10604317e+10],
       [1.10609983e+10],
       [1.10641736e+10],
       [1.10729679e+10],
       [1.10644229e+10],
       [1.11107822e+10],
       [1.11006279e+10],
       [1.11003559e+10],
       [1.10975681e+10],
       [1.11013079e+10],
       [1.10995173e+10],
       [1.10983840e+10],
       [1.11011946e+10],
       [1.10992453e+10],
       [1.10989507e+10],
       [1.11027812e+10],
       [1.10980214e+10],


In [202]:
v_1

array([[1.62095382e+18],
       [6.52790868e+18],
       [1.43090772e+18],
       [2.91061509e+19],
       [4.24251977e+18],
       [6.62454027e+18],
       [6.87368762e+18],
       [8.09664362e+18],
       [7.40735878e+18],
       [2.71811984e+18],
       [1.45176333e+19],
       [1.83899614e+18],
       [1.69211194e+18],
       [1.54253149e+18],
       [1.34839293e+19],
       [6.47416949e+18],
       [1.02814109e+18],
       [3.23052411e+19],
       [2.30152682e+18],
       [9.58859572e+17],
       [1.69966254e+18],
       [8.22871421e+17],
       [2.11526153e+18],
       [1.59517919e+18],
       [5.35021609e+18],
       [5.34439277e+18],
       [1.21198128e+19],
       [1.45420220e+18],
       [5.68308411e+18],
       [2.07322399e+19],
       [2.99761334e+18],
       [1.02159808e+18],
       [3.06210589e+18],
       [1.78003988e+18],
       [2.35802564e+18],
       [2.72116123e+18],
       [1.60966012e+18],
       [1.07950174e+19],
       [1.24007743e+19],
       [2.06578845e+18],


In [199]:
v_1.shape

(1, 496)

In [193]:
v_1

array([[-2.90368228e+16,  2.94586356e+15],
       [-1.17944382e+17,  1.18624352e+16],
       [-2.56313352e+16,  2.60048183e+15],
       [-5.19129246e+17,  5.28990671e+16],
       [-7.64107587e+16,  7.70973147e+15],
       [-1.18784689e+17,  1.20390694e+16],
       [-1.22541801e+17,  1.24926689e+16],
       [-1.43987790e+17,  1.47157535e+16],
       [-1.33357094e+17,  1.34611069e+16],
       [-4.87992469e+16,  4.93968977e+15],
       [-2.61225655e+17,  2.63824944e+16],
       [-3.28505517e+16,  3.34223136e+15],
       [-3.01958562e+16,  3.07531616e+15],
       [-2.75388499e+16,  2.80344825e+15],
       [-2.39490344e+17,  2.45075611e+16],
       [-1.15913427e+17,  1.17659942e+16],
       [-1.84728524e+16,  1.86844355e+15],
       [-5.72665249e+17,  5.87172949e+16],
       [-4.10338083e+16,  4.18293513e+15],
       [-1.71432927e+16,  1.74263508e+15],
       [-3.04151761e+16,  3.08894213e+15],
       [-1.45903959e+16,  1.49562885e+15],
       [-3.74801358e+16,  3.84467164e+15],
       [-2.

In [192]:
v_1.shape

(496, 2)

In [190]:
f_k.shape

(2, 14)

In [194]:
mat_2.shape

(14, 496)

In [186]:
e_yy.shape

(14, 14)

In [174]:
e_xx

array([[6.13650350e-05, 7.60894130e-07],
       [7.60894130e-07, 1.55251535e-01]])

In [173]:
final_1

array([[1.11425720e+10],
       [1.11440226e+10],
       [1.11421187e+10],
       [1.11805825e+10],
       [1.11492131e+10],
       [1.11445213e+10],
       [1.11466292e+10],
       [1.11479891e+10],
       [1.11446573e+10],
       [1.11435240e+10],
       [1.11460172e+10],
       [1.11427080e+10],
       [1.11426627e+10],
       [1.11437507e+10],
       [1.10718325e+10],
       [1.10607036e+10],
       [1.10594797e+10],
       [1.10744164e+10],
       [1.10599557e+10],
       [1.10592077e+10],
       [1.10600917e+10],
       [1.10582557e+10],
       [1.10586637e+10],
       [1.10604317e+10],
       [1.10609983e+10],
       [1.10641736e+10],
       [1.10729679e+10],
       [1.10644229e+10],
       [1.11107822e+10],
       [1.11006279e+10],
       [1.11003559e+10],
       [1.10975681e+10],
       [1.11013079e+10],
       [1.10995173e+10],
       [1.10983840e+10],
       [1.11011946e+10],
       [1.10992453e+10],
       [1.10989507e+10],
       [1.11027812e+10],
       [1.10980214e+10],


In [167]:
e_xx_1.T

array([[1.62958830e+04, 1.86532194e+01],
       [1.86532194e+01, 6.46251166e+00]])

In [149]:
w_S.

(2,)

In [144]:
m4

array([[8.93388583e-01, 2.92418986e+00],
       [2.92418986e+00, 3.50469143e+03]])

In [143]:
s_yy.shape

(14, 14)

In [140]:
w_yy

array([ 1.67673677e+09+0.00000000e+00j, -1.72396014e+08+0.00000000e+00j,
        1.97060505e+07+2.07430006e+07j,  1.97060505e+07-2.07430006e+07j,
       -1.28223813e+06+0.00000000e+00j,  7.66546574e+05+0.00000000e+00j,
       -2.47255743e+04+0.00000000e+00j,  2.34262983e+03+1.95933355e+03j,
        2.34262983e+03-1.95933355e+03j, -1.88296855e+03+0.00000000e+00j,
       -2.46037408e+02+0.00000000e+00j,  2.17076482e+00+0.00000000e+00j,
        1.94029005e+00+5.66845762e+00j,  1.94029005e+00-5.66845762e+00j])

In [125]:
dataset

0         1    \
Page total likes                                    139441.0  139441.0   
Category                                                 2.0       2.0   
Post Month                                              12.0      12.0   
Post Weekday                                             4.0       3.0   
Post Hour                                                3.0      10.0   
Lifetime Post Total Reach                             2752.0   10460.0   
Lifetime Post Total Impressions                       5091.0   19057.0   
Lifetime Engaged Users                                 178.0    1457.0   
Lifetime Post Consumers                                109.0    1361.0   
Lifetime Post Consumptions                             159.0    1674.0   
Lifetime Post Impressions by people who have li...    3078.0   11710.0   
Lifetime Post reach by people who like your Page      1640.0    6112.0   
Lifetime People who have liked your Page and en...     119.0    1108.0   
comment                                                  4.0       5.0   
like                                                    79.0     130.0   
share                                                   17.0      29.0   
Total Interactions                                     100.0     164.0   

                                                         2         3    \
Page total likes                                    139441.0  139441.0   
Category                                                 3.0       2.0   
Post Month                                              12.0      12.0   
Post Weekday                                             3.0       2.0   
Post Hour                                                3.0      10.0   
Lifetime Post Total Reach                             2413.0   50128.0   
Lifetime Post Total Impressions                       4373.0   87991.0   
Lifetime Engaged Users                                 177.0    2211.0   
Lifetime Post Consumers                                113.0     790.0   
Lifetime Post Consumptions                             154.0    1119.0   
Lifetime Post Impressions by people who have li...    2812.0   61027.0   
Lifetime Post reach by people who like your Page      1503.0   32048.0   
Lifetime People who have liked your Page and en...     132.0    1386.0   
comment                                                  0.0      58.0   
like                                                    66.0    1572.0   
share                                                   14.0     147.0   
Total Interactions                                      80.0    1777.0   

                                                         4         5    \
Page total likes                                    139441.0  139441.0   
Category                                                 2.0       2.0   
Post Month                                              12.0      12.0   
Post Weekday                                             2.0       1.0   
Post Hour                                                3.0       9.0   
Lifetime Post Total Reach                             7244.0   10472.0   
Lifetime Post Total Impressions                      13594.0   20849.0   
Lifetime Engaged Users                                 671.0    1191.0   
Lifetime Post Consumers                                410.0    1073.0   
Lifetime Post Consumptions                             580.0    1389.0   
Lifetime Post Impressions by people who have li...    6228.0   16034.0   
Lifetime Post reach by people who like your Page      3200.0    7852.0   
Lifetime People who have liked your Page and en...     396.0    1016.0   
comment                                                 19.0       1.0   
like                                                   325.0     152.0   
share                                                   49.0      33.0   
Total Interactions                                     393.0     186.0   

                                                         6

In [109]:
w_S

array([-2.24918621e+00+7.03226151e-18j,  2.15013026e+09-1.65910959e-08j])

In [95]:
np.matmul(np.matmul(np.matmul(w_xx_inv_p,s_yx),w_yy_inv_p),s_xy)

array([[ 1.30409445e+08+1.11260394e+08j, -7.57520563e+06-6.45244302e+06j],
       [-1.91649987e+10-1.63244496e+10j,  1.12442668e+09+1.43236001e+09j]])

In [96]:
w_xx_inv_p = np.diag(w_xx_inv).reshape(2,2)

In [97]:
w_xx_inv_p

array([[6.13651123e-05, 0.00000000e+00],
       [0.00000000e+00, 1.55251535e-01]])

In [102]:
s_xy.shape

(14, 2)

In [101]:
w_yy_inv_p.shape

(14, 14)

In [83]:
s_yy.shape

(14, 14)

In [84]:
s_yy

array([[-3.43629847e-01,  1.09694363e+01,  6.65363311e-02,
        -2.57513848e+00, -7.48566686e+03, -2.54065877e+04,
        -3.64807657e+02, -4.19542880e+02, -9.26889606e+02,
        -1.85274155e+04, -2.22835598e+03,  3.21752036e+01,
         6.01335940e-01,  3.03257739e+01],
       [-7.78755295e-02,  6.65363311e-02,  4.11559140e+00,
         4.09652981e-01, -2.11093394e+03, -4.81326101e+03,
        -8.54555963e+01, -4.33878543e+01, -6.83877322e+01,
        -5.42035193e+03, -9.80465616e+02,  8.82169273e+00,
        -3.21978658e+00, -5.21108504e+01],
       [-4.00293255e-01, -2.57513848e+00,  4.09652981e-01,
         1.92197418e+01,  3.76782283e+02,  4.40324954e+03,
         1.90141455e+01,  4.93350481e+01,  6.97515339e+02,
         1.02908678e+04,  1.79205353e+03,  1.03939952e+02,
         1.10968557e-01, -3.44133594e+01],
       [-2.87036833e+03, -7.48566686e+03, -2.11093394e+03,
         3.76782283e+02,  5.19943419e+08,  1.22057840e+09,
         1.28099540e+07,  9.60542687e+06,  1.

In [79]:
S

array([-2.08984542e+00-1.83582391e+00j,  1.30653325e+06+1.77717449e+06j])

In [74]:
w_xx_inv_p.shape


(2, 2)

In [75]:
s_xy.shape

(14, 2)

In [65]:
w_yy

array([ 1.67673677e+09+0.00000000e+00j, -1.72396014e+08+0.00000000e+00j,
        1.97060505e+07+2.07430006e+07j,  1.97060505e+07-2.07430006e+07j,
       -1.28223813e+06+0.00000000e+00j,  7.66546574e+05+0.00000000e+00j,
       -2.47255743e+04+0.00000000e+00j,  2.34262983e+03+1.95933355e+03j,
        2.34262983e+03-1.95933355e+03j, -1.88296855e+03+0.00000000e+00j,
       -2.46037408e+02+0.00000000e+00j,  1.94029000e+00+5.66845760e+00j,
        1.94029000e+00-5.66845760e+00j,  2.17076485e+00+0.00000000e+00j])

In [66]:
w_yy_inv_p

array([[2.44212313e-05+0.00000000e+00j, 0.00000000e+00+0.00000000e+00j,
        0.00000000e+00+0.00000000e+00j, 0.00000000e+00+0.00000000e+00j,
        0.00000000e+00+0.00000000e+00j, 0.00000000e+00+0.00000000e+00j,
        0.00000000e+00+0.00000000e+00j, 0.00000000e+00+0.00000000e+00j,
        0.00000000e+00+0.00000000e+00j, 0.00000000e+00+0.00000000e+00j,
        0.00000000e+00+0.00000000e+00j, 0.00000000e+00+0.00000000e+00j,
        0.00000000e+00+0.00000000e+00j, 0.00000000e+00+0.00000000e+00j],
       [0.00000000e+00+0.00000000e+00j, 4.66355653e-21-7.61616580e-05j,
        0.00000000e+00+0.00000000e+00j, 0.00000000e+00+0.00000000e+00j,
        0.00000000e+00+0.00000000e+00j, 0.00000000e+00+0.00000000e+00j,
        0.00000000e+00+0.00000000e+00j, 0.00000000e+00+0.00000000e+00j,
        0.00000000e+00+0.00000000e+00j, 0.00000000e+00+0.00000000e+00j,
        0.00000000e+00+0.00000000e+00j, 0.00000000e+00+0.00000000e+00j,
        0.00000000e+00+0.00000000e+00j, 0.00000000e+00+0.000000

In [45]:
p

array([2.65556498e+08, 4.14885442e+01])

In [46]:
p.shape

(2,)

In [67]:
w_yy

array([ 1.67673677e+09+0.00000000e+00j, -1.72396014e+08+0.00000000e+00j,
        1.97060505e+07+2.07430006e+07j,  1.97060505e+07-2.07430006e+07j,
       -1.28223813e+06+0.00000000e+00j,  7.66546574e+05+0.00000000e+00j,
       -2.47255743e+04+0.00000000e+00j,  2.34262983e+03+1.95933355e+03j,
        2.34262983e+03-1.95933355e+03j, -1.88296855e+03+0.00000000e+00j,
       -2.46037408e+02+0.00000000e+00j,  1.94029000e+00+5.66845760e+00j,
        1.94029000e+00-5.66845760e+00j,  2.17076485e+00+0.00000000e+00j])

In [40]:
v

array([[ 1.00000000e+00, -1.14465590e-03],
       [-4.44860168e-06,  9.99999345e-01]])

In [33]:
s_yy

array([[-3.43629847e-01,  1.09694363e+01,  6.65363311e-02,
        -2.57513848e+00, -7.48566686e+03, -2.54065877e+04,
        -3.64807657e+02, -4.19542880e+02, -9.26889606e+02,
        -1.85274155e+04, -2.22835598e+03,  3.21752036e+01,
         6.01335940e-01,  3.03257739e+01],
       [-7.78755295e-02,  6.65363311e-02,  4.11559140e+00,
         4.09652981e-01, -2.11093394e+03, -4.81326101e+03,
        -8.54555963e+01, -4.33878543e+01, -6.83877322e+01,
        -5.42035193e+03, -9.80465616e+02,  8.82169273e+00,
        -3.21978658e+00, -5.21108504e+01],
       [-4.00293255e-01, -2.57513848e+00,  4.09652981e-01,
         1.92197418e+01,  3.76782283e+02,  4.40324954e+03,
         1.90141455e+01,  4.93350481e+01,  6.97515339e+02,
         1.02908678e+04,  1.79205353e+03,  1.03939952e+02,
         1.10968557e-01, -3.44133594e+01],
       [-2.87036833e+03, -7.48566686e+03, -2.11093394e+03,
         3.76782283e+02,  5.19943419e+08,  1.22057840e+09,
         1.28099540e+07,  9.60542687e+06,  1.

In [34]:
s_xy

array([[-3.43629847e-01, -3.08510916e+00],
       [-7.78755295e-02, -4.21124145e+00],
       [-4.00293255e-01, -1.09625122e+01],
       [-2.87036833e+03,  4.43389017e+05],
       [-6.43041147e+03,  9.42025288e+05],
       [-2.24336918e+00,  2.23410524e+04],
       [-2.79291300e+01,  1.29282263e+04],
       [-2.65356598e+02,  1.72064892e+04],
       [-2.56667550e+03,  4.84287496e+05],
       [-7.31443500e+02,  1.59582127e+05],
       [ 8.20589769e+00,  1.14934616e+04],
       [ 4.53274682e-01,  7.86513962e+02],
       [ 3.42630173e+01,  1.24858248e+04],
       [ 5.42000652e+00,  1.81589267e+03],
       [ 4.01362985e+01,  1.50882314e+04]])

In [35]:
s_xx

array([[ 2.65556499e+08,  3.03970965e+05],
       [-1.18135490e+03,  4.01362985e+01]])

In [36]:
cov_mat

array([[ 2.65556499e+08, -1.18135490e+03,  5.07834184e+04,
        -4.05315559e+02, -1.03457353e+04, -2.96719695e+07,
        -1.26219139e+08, -1.73243800e+06, -2.09522368e+06,
        -4.08428140e+06, -9.26379924e+07, -7.00808172e+06,
         3.85630156e+05,  1.18756692e+04,  2.95469230e+05,
        -3.37393415e+03,  3.03970965e+05],
       [-1.18135490e+03,  7.26621049e-01, -3.43629847e-01,
        -7.78755295e-02, -4.00293255e-01, -2.87036833e+03,
        -6.43041147e+03, -2.24336918e+00, -2.79291300e+01,
        -2.65356598e+02, -2.56667550e+03, -7.31443500e+02,
         8.20589769e+00,  4.53274682e-01,  3.42630173e+01,
         5.42000652e+00,  4.01362985e+01],
       [ 5.07834184e+04, -3.43629847e-01,  1.09694363e+01,
         6.65363311e-02, -2.57513848e+00, -7.48566686e+03,
        -2.54065877e+04, -3.64807657e+02, -4.19542880e+02,
        -9.26889606e+02, -1.85274155e+04, -2.22835598e+03,
         3.21752036e+01,  6.01335940e-01,  3.03257739e+01,
        -3.08510916e+00,  2.7

In [60]:
s_yy.shape


(15, 14)

In [61]:
cov_mat.shape

(17, 17)

In [62]:
s_xx.shape

(2, 2)