In [31]:
import numpy as np
import pandas as pd
import seaborn as sb
from scipy.cluster.vq import vq, kmeans, whiten

dataset = pd.read_csv('Facebook_metrics/dataset_Facebook.csv',delimiter=';')
del dataset['Page total likes']
del dataset['Type']
del dataset['Paid']
del dataset['Total Interactions']
dataset = dataset.dropna(how='any',axis=0)
#dataset = dataset.T
features = np.array(dataset)
whitened = whiten(features)
for i in range(3):
    book = np.array((whitened[i],))
    print(kmeans(whitened,book,iter=100,thresh=1e-05))


(array([[2.21604423, 2.12052624, 2.03936188, 1.78935837, 0.61495658,
        0.387193  , 0.93938713, 0.90956674, 0.71090517, 0.28170756,
        0.86277293, 1.00045984, 0.35519844, 0.55274219, 0.64049632]]), 3.066795199212523)
(array([[2.21604423, 2.12052624, 2.03936188, 1.78935837, 0.61495658,
        0.387193  , 0.93938713, 0.90956674, 0.71090517, 0.28170756,
        0.86277293, 1.00045984, 0.35519844, 0.55274219, 0.64049632]]), 3.066795199212523)
(array([[2.21604423, 2.12052624, 2.03936188, 1.78935837, 0.61495658,
        0.387193  , 0.93938713, 0.90956674, 0.71090517, 0.28170756,
        0.86277293, 1.00045984, 0.35519844, 0.55274219, 0.64049632]]), 3.066795199212523)
